version: '3'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    ports:
      - "23306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: itcast
      MYSQL_USER: root
      MYSQL_PASSWORD: 1234
volumes:
  mysql_data: