global:
  scrape_interval: 15s  # 기본 스크랩 간격
  evaluation_interval: 15s  # 룰 평가 간격

scrape_configs:
  - job_name: 'b2c'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080']

  - job_name: 'schedule'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8081']

  - job_name: 'admin'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8082']
