server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          __path__: /var/log/*.log

  - job_name: admin_logs_warn
    static_configs:
      - targets:
          - http://loki:3100
        labels:
          job: admin_logs_warn
          __path__: /admin/logs/warn/warn.log

  - job_name: admin_logs_error
    static_configs:
      - targets:
          - http://loki:3100
        labels:
          job: admin_logs_error
          __path__: /admin/logs/error/error.log

  - job_name: admin_logs_info
    static_configs:
      - targets:
          - http://loki:3100
        labels:
          job: admin_logs_info
          __path__: /admin/logs/info/info.log

  - job_name: b2c_logs_warn
    static_configs:
      - targets:
          - http://loki:3100
        labels:
          job: b2c_logs_warn
          __path__: /b2c/logs/warn/warn.log

  - job_name: b2c_logs_error
    static_configs:
      - targets:
          - http://loki:3100
        labels:
          job: b2c_logs_error
          __path__: /b2c/logs/error/error.log

  - job_name: b2c_logs_info
    static_configs:
      - targets:
          - http://loki:3100
        labels:
          job: b2c_logs_info
          __path__: /b2c/logs/info/info.log
