name: ItcastBuildAndDeploy

on:
  workflow_run:
    workflows: ["ItcastBuildAndTest"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: echo "Triggered"

